name: DevSecOps Pipeline - Hackers do Bem

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-with: '3.10'

    - name: Instalar Dependências
      run: |
        pip install -r requirements.txt

  security-sast:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3

    - name: Rodar Análise Estática (Bandit)
      run: |
        pip install bandit
        bandit -r . -f txt -o bandit-report.txt || true

  deploy-and-delivery:
    needs: security-sast
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3

    - name: Simulando o Deploy Contínuo (CD)
      run: |
        echo "Gerando artefato de entrega..."
        echo "Fazendo o Deploy para o ambiente de Homologação/Stage..."
        echo "Deploy processado com sucesso!"
